model_type: "variational"  # "vanilla" or "variational"
threshold: 16
learning_rate: 0.001
batch_size: 512
config:
  - type: Conv
    in_channels: 3
    out_channels: 32
    kernel_size: 7
    stride: 2
    # dim : 48 -> 24

  - type: Conv
    in_channels: 32
    out_channels: 64
    kernel_size: 5
    stride: 2
    # dim : 24 -> 12

  - type: Conv
    in_channels: 64
    out_channels: 128
    kernel_size: 5
    stride: 2
    # dim : 12 -> 6
  
  - type: Conv
    in_channels: 128
    out_channels: 256
    kernel_size: 3
    stride: 2
    # dim : 6 -> 3
  
  - type: Conv
    in_channels: 256
    out_channels: 512
    kernel_size: 3
    stride: 3
    # dim : 3 -> 1

  - type: Flatten
    in_channels: 512
    in_size: 1
    out_features: 512

  - type: Linear
    in_features: 512
    out_features: 64
    activation: "LeakyReLU"
  
  - type: Linear
    in_features: 64
    out_features: 8
    activation: None
